init:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - SET RAKEOPT=-rdevkit
install:
  - ruby --version
  - gem --version
  - bundle install
  - ps: |
      if ($env:PGVERSION -ne $null)
      {
        $(new-object net.webclient).DownloadFile('http://get.enterprisedb.com/postgresql/postgresql-' + $env:PGVERSION + '.exe', 'C:\postgresql-setup.exe')
        cmd /c C:\postgresql-setup.exe --mode unattended --extract-only 1
      }
      $env:PATH = 'C:\Program Files\PostgreSQL\' + $env:PGVER + '\bin;' + $env:PATH
      $env:PATH = 'C:\Program Files (x86)\PostgreSQL\' + $env:PGVER + '\bin;' + $env:PATH
build_script:
  - bundle exec rake compile
test_script:
  - bundle exec rake test
environment:
  matrix:
    - ruby_version: "22"
      PGVERSION: 9.1.19-3-windows
      PGVER: 9.1
    - ruby_version: "22-x64"
      PGVER: 9.4
    - ruby_version: "23"
      PGVERSION: 9.5.0-1-windows
      PGVER: 9.5
    - ruby_version: "23-x64"
      PGVERSION: 9.5.0-1-windows-x64
      PGVER: 9.5
